[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.20.4"
  NPM_FLAGS = "--production=false"

[[headers]]
  for = "/static/*"
  [headers.values]
    cache-control = "max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    cache-control = "max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    cache-control = "max-age=31536000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
